[package]
name = "rust-hyper-demo"
version = "0.1.0"
authors = ["stuartrobinson"]
edition = "2018"


[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
pretty_env_logger = "0.3"
